ADMIN_USER: ENC[AES256_GCM,data:NDNhk9AebAU2hw==,iv:2PSD8f5KrjtFih0wvEMyhJIPXrPOBRFIH2REY7UaytM=,tag:tJ/1flG1xsnFHn/CQzD78A==,type:str]
BACKUP_STORAGE: ""
DOMAIN: ""
GITHUB_ORG: ""
GITHUB_REPO: ""
LOKI_RETENTION: ""
PROMETHEUS_RETENTION: ""
PROXMOX_HOST_IP: ""
PROXMOX_NODE: ""
PROXMOX_REALM: ""
PROXMOX_SSH_KEY_NAME: ""
PROXMOX_SSH_USER: ""
PROXMOX_STORAGE: ""
PROXMOX_TOKEN_ID: ""
PROXMOX_TOKEN_SECRET: ""
PROXMOX_USER: ""
PVE_TOKEN_NAME: ""
PVE_USER: ""
SECRETS_AUTHENTIK_PG_PASS: ""
SECRETS_AUTHENTIK_SECRET_KEY: ""
SECRETS_CADDY_CLOUDFLARE_API_TOKEN: ""
SECRETS_CLOUDFLARED_CREDENTIALS_JSON: ""
SECRETS_CLOUDFLARED_TUNNEL_ID: ""
SECRETS_GH_RUNNER_COMPOSE_PAT_TOKEN: ""
SECRETS_KOMODO_DATABASE_PASSWORD: ""
SECRETS_KOMODO_INIT_ADMIN_PASSWORD: ""
SECRETS_KOMODO_JWT_SECRET: ""
SECRETS_KOMODO_WEBHOOK_SECRET: ""
SECRETS_MONITORING_GRAFANA_ADMIN_PASSWORD: ""
SECRETS_MONITORING_PVE_EXPORTER_TOKEN_VALUE: ""
SECRETS_PROXMOX_API_TOKEN: ""
TIMEZONE: ""
sops:
    age:
        - recipient: age10k6zx49jwuyp8htq0fw6u8lvnqj0nuecpdkl7vjupll29sxf69jq4la7c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT3RtM241VVF6dmMrUlhQ
            RzlJM0U0UE5DUnhKVDM2dXEybzhYdzNRVGlrCm90UzFybTFiUHhsRlpyMW5zTVlh
            OWhhY0dpb2x3RlZJVGtWZFhzTWtKNlEKLS0tIFZtQ2kwTUY4MDNHTlp5ekM3ZWRM
            OEhGZTR2WTAyTlhVRXpqT3FKVmF0akkKGDA8ZvZSj5FEP2ZeHuJKgVm/Te7FRoLE
            5o+9XEcFqLQLW+NpoG4fqJj3HwwBLbs0+DYp7gM0JYaa7TERpBN5tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-28T09:22:56Z"
    mac: ENC[AES256_GCM,data:AdtLLMfms9rFut+y6dV6TFGjImQuxtl+vvwK6ezYjXrbZteT1RE9FG4qQYeJtCh5afPR8WMSN9CUqjxnWjxuUaReHVHMMVz6vdoWVgiNSi0/pZfYN1w+8p3izd8WdDX6bYwVL16fecg6dKdD4hSwh/WNbWNgiTvBb55ts5C8lLY=,iv:q8GUeq238/oTICwaGcMLPgKskcSobyDf8Cj5rxU6fwM=,tag:mhFhedEEEmKfNN6lDAt6FA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
