ADMIN_USER: ENC[AES256_GCM,data:NDNhk9AebAU2hw==,iv:2PSD8f5KrjtFih0wvEMyhJIPXrPOBRFIH2REY7UaytM=,tag:tJ/1flG1xsnFHn/CQzD78A==,type:str]
BACKUP_STORAGE: ""
DOMAIN: ""
GITHUB_ORG: ""
GITHUB_REPO: ""
LOKI_RETENTION: ""
PROMETHEUS_RETENTION: ""
PROXMOX_HOST_IP: ""
PROXMOX_NODE: ""
PROXMOX_REALM: ""
PROXMOX_SSH_KEY_NAME: ""
PROXMOX_SSH_USER: ""
PROXMOX_STORAGE: ""
PROXMOX_TOKEN_ID: ""
PROXMOX_TOKEN_SECRET: ""
PROXMOX_USER: ""
PVE_TOKEN_NAME: ""
PVE_USER: ""
SECRETS_AUTHENTIK_PG_PASS: ""
SECRETS_AUTHENTIK_SECRET_KEY: ""
SECRETS_CADDY_CLOUDFLARE_API_TOKEN: ""
SECRETS_CLOUDFLARED_CREDENTIALS_JSON: ""
SECRETS_CLOUDFLARED_TUNNEL_ID: ""
SECRETS_GH_RUNNER_COMPOSE_PAT_TOKEN: ""
SECRETS_KOMODO_DATABASE_PASSWORD: ""
SECRETS_KOMODO_INIT_ADMIN_PASSWORD: ""
SECRETS_KOMODO_JWT_SECRET: ""
SECRETS_KOMODO_WEBHOOK_SECRET: ""
SECRETS_MONITORING_GRAFANA_ADMIN_PASSWORD: ""
SECRETS_MONITORING_PVE_EXPORTER_TOKEN_VALUE: ""
SECRETS_PROXMOX_API_TOKEN: ""
TIMEZONE: ""
S3_ACCESS_KEY: ENC[AES256_GCM,data:gCdwOSGI6PW3mjrzPY2m3TRxhezV43h6pIonDuEROVk=,iv:4x3NlPOQ4hQZaqRAtWA5zLxUPxhZ9VXnvApdYX/EG5s=,tag:FgIMGA4v/h60fZQwPnXrxw==,type:str]
S3_SECRET_KEY: ENC[AES256_GCM,data:rs8+Zn9sWWG1eiXjxQyn2Q7n5ymCJ7vXrbqL/bNiL+tWtzz+wuDTp7fNe2DJu9FFLewAc6AZQArmbdxC7tCBgw==,iv:pLxXewMXdESWc6P9oBfsMNSshdYcqtEPRO/x+aLAY1s=,tag:hbGMQlKEd/4+PyAT8M26KA==,type:str]
sops:
    age:
        - recipient: age10k6zx49jwuyp8htq0fw6u8lvnqj0nuecpdkl7vjupll29sxf69jq4la7c3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWT3RtM241VVF6dmMrUlhQ
            RzlJM0U0UE5DUnhKVDM2dXEybzhYdzNRVGlrCm90UzFybTFiUHhsRlpyMW5zTVlh
            OWhhY0dpb2x3RlZJVGtWZFhzTWtKNlEKLS0tIFZtQ2kwTUY4MDNHTlp5ekM3ZWRM
            OEhGZTR2WTAyTlhVRXpqT3FKVmF0akkKGDA8ZvZSj5FEP2ZeHuJKgVm/Te7FRoLE
            5o+9XEcFqLQLW+NpoG4fqJj3HwwBLbs0+DYp7gM0JYaa7TERpBN5tA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-02T12:07:31Z"
    mac: ENC[AES256_GCM,data:6uw/0IW5P1XYNxltVB5uLjEKXVqK6GdWuHcUE5JG3YEq6t+JqjUMIslIO/VvzsYlJwYmDMs5EaW6DJUF/FtGRT9tlvBxCuUfJlms/BxcNtSSktp3Uf3okGt15N9F12NKdjbksV+oIYpNnHzCFEn/mrHTpR1yYivj8Rt3YaF/Hc4=,iv:cOMyHcMfDKVPzs6zr9Gw3wNacy2zXgf00w5wuzy4t18=,tag:TYPJpu2Y+QjYk7Qaz4UriA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
