ADMIN_USER: "admin"
BACKUP_STORAGE: "local"
DOMAIN: ""
GITHUB_ORG: ""
GITHUB_REPO: ""
LOKI_RETENTION: "15d"
PROMETHEUS_RETENTION: "15d"
PROXMOX_HOST_IP: ""
PROXMOX_NODE: "pve"
PROXMOX_REALM: "pam"
PROXMOX_SSH_KEY_NAME: "proxmox_terraform"
PROXMOX_SSH_USER: "root"
PROXMOX_STORAGE: "local-lvm"
PROXMOX_TOKEN_ID: "terraform"
PROXMOX_TOKEN_SECRET: ""
PROXMOX_USER: "root@pam"
PVE_TOKEN_NAME: "prometheus"
PVE_USER: "prometheus@pve"
SECRETS_AUTHENTIK_PG_PASS: ""
SECRETS_AUTHENTIK_SECRET_KEY: ""
SECRETS_CADDY_CLOUDFLARE_API_TOKEN: ""
SECRETS_CLOUDFLARED_CREDENTIALS_JSON: ""
SECRETS_CLOUDFLARED_TUNNEL_ID: ""
SECRETS_GH_RUNNER_COMPOSE_PAT_TOKEN: ""
SECRETS_KOMODO_DATABASE_PASSWORD: ""
SECRETS_KOMODO_INIT_ADMIN_PASSWORD: ""
SECRETS_KOMODO_JWT_SECRET: ""
SECRETS_KOMODO_WEBHOOK_SECRET: ""
SECRETS_MONITORING_GRAFANA_ADMIN_PASSWORD: ""
SECRETS_MONITORING_PVE_EXPORTER_TOKEN_VALUE: ""
SECRETS_PROXMOX_API_TOKEN: ""
TIMEZONE: "Europe/Paris"
S3_ACCESS_KEY: ""
S3_SECRET_KEY: ""
