version: '3.8'

services:
  rustfs:
    image: rustfs/rustfs:latest
    env_file:
      - .env
    environment:
      RUSTFS_ACCESS_KEY: ${S3_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${S3_SECRET_KEY}
    command: server /data
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - rustfs_data:/data

  mc-init:
    image: minio/mc
    depends_on:
      - rustfs
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://rustfs:9000 $${S3_ACCESS_KEY} $${S3_SECRET_KEY};
      mc mb local/terraform-state || true;
      "

  terraboard:
    image: camptocamp/terraboard:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: terraboard
      DB_USER: root
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_SSLMODE: disable
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
      AWS_REGION: us-east-1
      AWS_ENDPOINTS: http://rustfs:9000
      AWS_S3_ENDPOINT: http://rustfs:9000
      S3_BUCKET: terraform-state
      S3_FORCE_PATH_STYLE: "true"
    depends_on:
      - db
      - mc-init

  db:
    image: postgres:16.10
    environment:
      POSTGRES_DB: terraboard
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  rustfs_data:
    driver: local
